source 'http://rubygems.org'
gem 'rails', '3.0.9'
gem 'sqlite3'
gem 'RedCloth'
gem 'will_paginate'
gem 'jquery-rails'
gem 'haml'
gem 'devise'
gem 'sass'
gem 'paperclip'
gem 'pony'
gem 'mysql2', '0.2.7'
gem 'capistrano'
gem 'bundle'
gem 'ruby-debug19'
